In [1]:
# Importing the relevant libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cleaned_rent.csv')

In [3]:
df.head()

Price  Bed  Bath  Toilet      Property Type  Area Purchase Type  \
0   800000.0  2.0   3.0     3.0   Flat / apartment  ajah          rent   
1   700000.0  1.0   2.0     2.0          Mini flat  ajah          rent   
2   900000.0  1.0   1.0     2.0          Mini flat  ajah          rent   
3  1100000.0  3.0   3.0     4.0   Flat / apartment  ajah          rent   
4  1800000.0  4.0   4.0     4.0  Detached bungalow  ajah          rent   

   Parking Space  Security  Electricity  Furnished  Security Doors  CCTV  BQ  \
0              0         0            0          0               0     0   0   
1              0         0            0          0               0     0   0   
2              0         0            0          0               0     0   0   
3              0         0            0          0               0     0   0   
4              1         0            0          1               0     0   1   

   Gym  Pool  
0    0     0  
1    0     0  
2    0     0  
3    0     0  
4    0     0

# Preprocessing the Data

In [4]:
df['Property Type'].value_counts()

Flat / apartment          15150
Mini flat                  6126
Self contain               2181
Blocks of flats            1719
Terraced duplex            1242
Semi detached duplex        838
Detached duplex             791
Penthouse flat              248
Detached bungalow           123
Massionette house            86
Semi detached bungalow       45
Terraced bungalow            13
Name: Property Type, dtype: int64

In [5]:
#Plot a bar chart
PropertyCounts = df['Property Type'].value_counts() 
%matplotlib inline
from matplotlib import pyplot as plt
PropertyCounts.plot(kind = 'bar', title = 'Property Type Counts')
plt.xlabel('Property Type')
plt.ylabel('Count')
plt.show()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [6]:
property_type = df.groupby('Property Type').agg(
    mean_price = pd.NamedAgg(column='Price', aggfunc =np.mean)
)   
property_type.head(15).sort_values(by=['mean_price'], ascending=False)

mean_price
Property Type                       
Massionette house       1.065372e+07
Terraced duplex         6.111601e+06
Detached duplex         4.775499e+06
Semi detached duplex    4.696241e+06
Penthouse flat          4.285081e+06
Terraced bungalow       2.300000e+06
Semi detached bungalow  2.260778e+06
Flat / apartment        2.213288e+06
Blocks of flats         1.574520e+06
Detached bungalow       1.465285e+06
Mini flat               6.243201e+05
Self contain            4.921175e+05

In [7]:
property_type.plot(kind = 'barh', title = 'Property Price Average Price')
plt.xlabel('Property Type')
plt.ylabel('Average Price')
plt.show()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [8]:
#Ranking 'Property Type' feature by increasing order of average price

cleanup_num = {"Property Type": {"Self contain": 0, "Mini flat": 1, "Detached bungalow": 2, "Blocks of flats": 3, "Flat / apartment": 4, "Semi detached bungalow": 5, "Terraced bungalow": 6
                                , "Penthouse flat": 7, "Semi detached duplex": 8, "Detached duplex": 9, "Terraced duplex": 10, "Massionette house": 11}}
df.replace(cleanup_num, inplace = True)

In [9]:
df['Property Type'].value_counts()

4     15150
1      6126
0      2181
3      1719
10     1242
8       838
9       791
7       248
2       123
11       86
5        45
6        13
Name: Property Type, dtype: int64

In [10]:
df['Area'].value_counts()

yaba        5656
ajah        5018
gbagada     3697
surulere    3494
ikeja       3480
ikoyi       3351
lekki       2798
ikorodu     1068
Name: Area, dtype: int64

In [11]:
AreaCounts = df['Area'].value_counts() 
AreaCounts.plot.pie(title = 'Area Counts')
plt.show()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [12]:
area= df.groupby('Area').agg(
    mean_price = pd.NamedAgg(column='Price', aggfunc =np.mean)
)   
area.head(10).sort_values(by=['mean_price'], ascending=False)

mean_price
Area                  
ikoyi     8.992768e+06
lekki     2.619115e+06
ikeja     1.869155e+06
gbagada   9.743197e+05
ajah      8.427131e+05
surulere  7.399671e+05
yaba      7.169887e+05
ikorodu   2.723146e+05

In [13]:
area.plot(kind = 'bar', title = 'Area')
plt.xlabel('Area')
plt.ylabel('mean Price')
plt.show()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [14]:
#Ranking 'Area' feature by increasing order of average price

cleanup_num_a = {"Area": {"ikorodu": 0, "yaba": 1, "surulere": 2, "ajah": 3, "gbagada": 4, "ikeja": 5, "lekki": 6, "ikoyi": 7}}
df.replace(cleanup_num_a, inplace = True)

In [15]:
df['Area'].value_counts()

1    5656
3    5018
4    3697
2    3494
5    3480
7    3351
6    2798
0    1068
Name: Area, dtype: int64

In [16]:
df['Purchase Type'].value_counts()

rent    28562
Name: Purchase Type, dtype: int64

In [17]:
df.shape

(28562, 16)

In [18]:
df.describe()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [19]:
df.isnull().sum()

Price             0
Bed               0
Bath              0
Toilet            0
Property Type     0
Area              0
Purchase Type     0
Parking Space     0
Security          0
Electricity       0
Furnished         0
Security Doors    0
CCTV              0
BQ                0
Gym               0
Pool              0
dtype: int64

In [20]:
df.dtypes

Price             float64
Bed               float64
Bath              float64
Toilet            float64
Property Type       int64
Area                int64
Purchase Type      object
Parking Space       int64
Security            int64
Electricity         int64
Furnished           int64
Security Doors      int64
CCTV                int64
BQ                  int64
Gym                 int64
Pool                int64
dtype: object

In [21]:
#Splitting data into feature and target, with a bit of feature selection

X = df.drop(['Price','Purchase Type'], axis = 1)
y = df['Price']

In [22]:
X.head()

Bed  Bath  Toilet  Property Type  Area  Parking Space  Security  \
0  2.0   3.0     3.0              4     3              0         0   
1  1.0   2.0     2.0              1     3              0         0   
2  1.0   1.0     2.0              1     3              0         0   
3  3.0   3.0     4.0              4     3              0         0   
4  4.0   4.0     4.0              2     3              1         0   

   Electricity  Furnished  Security Doors  CCTV  BQ  Gym  Pool  
0            0          0               0     0   0    0     0  
1            0          0               0     0   0    0     0  
2            0          0               0     0   0    0     0  
3            0          0               0     0   0    0     0  
4            0          1               0     0   1    0     0

In [23]:
y.head()

0     800000.0
1     700000.0
2     900000.0
3    1100000.0
4    1800000.0
Name: Price, dtype: float64

In [60]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 5)

# Modelling Using Random Forest Regressor

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
rf = Pipeline(steps=[('Regressor', RandomForestRegressor())])

In [62]:
rf.fit(X_train, y_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('Regressor',
                 RandomForestRegressor(bootstrap=True, criterion='mse',
                                       max_depth=None, max_features='auto',
                                       max_leaf_nodes=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=10, n_jobs=None,
                                       oob_score=False, random_state=None,
                                       verbose=0, warm_start=False))],
         verbose=False)

In [63]:
#Predicting the test set results
y_pred = rf.predict(X_test)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)


In [64]:
y_pred

array([ 364816.00877193, 1278951.93476115, 8002584.1700836 , ...,
       1240000.        , 6997254.38958847, 3415000.        ])

In [65]:
rf.predict(X_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)


array([ 707083.33333333, 8002584.1700836 ,  303416.43572926, ...,
        728796.53205011,  650000.        ,  303416.43572926])

In [66]:
#model evaluation for training set

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


rmse = (np.sqrt(mean_squared_error(y_test, y_pred)))
r2 = r2_score(y_test, y_pred)

print("The model performance for training set")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

The model performance for training set
--------------------------------------
RMSE is 1482920.741685647
R2 score is 0.7759831186057776




#### Using Gradient Boost Algorithm

In [75]:
from sklearn.ensemble import GradientBoostingRegressor

In [83]:
sec_model = GradientBoostingRegressor(random_state = 3)

In [84]:
sec_model.fit(X_train, y_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1348: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.object)
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1570: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sample_mask = np.ones((n_samples, ), dtype=np.bool)
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1206: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert sample_mask.dtype == np.bool
C:\Users\USER\

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto', random_state=3,
                          subsample=1.0, tol=0.0001, validation_fraction=0.1,
                          verbose=0, warm_start=False)

In [85]:
sec_model.score(X_test, y_test)

0.7986577485036066

In [86]:
sec_model.predict(X_test[1:2])

array([910570.0241694])

In [87]:
n_pred = sec_model.predict(X_test)

In [90]:
n_pred

array([ 413464.06952034,  910570.0241694 , 7083326.34708334, ...,
       1611082.55456261, 6303857.52799198, 3734664.18342831])

In [88]:
mse = mean_squared_error(y_test,n_pred)
mse

1976469210229.383

In [89]:
root_mse = np.sqrt(mse)
root_mse

1405869.556619455